"""
core/utils.py
Pure utility functions for ApplyX.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
from typing import Any, Dict


_PBKDF2_ITERATIONS = 210_000
_LEGACY_SALT = b"applyx_salt_2026"


def hash_password(password: str) -> str:
    """Create a versioned PBKDF2-HMAC-SHA256 password hash with a random salt."""
    if not isinstance(password, str) or not password:
        raise ValueError("Password must be a non-empty string.")

    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, _PBKDF2_ITERATIONS)
    return "pbkdf2_sha256${}${}${}".format(
        _PBKDF2_ITERATIONS,
        base64.urlsafe_b64encode(salt).decode("ascii"),
        base64.urlsafe_b64encode(digest).decode("ascii"),
    )


def verify_password(password: str, stored_hash: str) -> bool:
    """Verify a current versioned hash, with compatibility for the old global-salt format."""
    if not isinstance(password, str) or not isinstance(stored_hash, str):
        return False

    try:
        if stored_hash.startswith("pbkdf2_sha256$"):
            scheme, iterations_text, salt_text, digest_text = stored_hash.split("$", 3)
            if scheme != "pbkdf2_sha256":
                return False
            iterations = int(iterations_text)
            salt = base64.urlsafe_b64decode(salt_text.encode("ascii"))
            expected = base64.urlsafe_b64decode(digest_text.encode("ascii"))
            actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, iterations)
            return hmac.compare_digest(actual, expected)

        # Legacy compatibility for hashes generated by the previous prototype.
        legacy = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), _LEGACY_SALT, 100_000).hex()
        return hmac.compare_digest(legacy, stored_hash)
    except (ValueError, TypeError, base64.binascii.Error):
        return False


def _is_known_nonempty(value: Any) -> bool:
    return value is not None and str(value).strip() != ""


def calculate_profile_completeness(profile: Dict[str, Any]) -> Dict[str, int]:
    """Compute mandatory and optional profile completeness percentages."""
    profile = profile or {}

    cgpa_value = None
    try:
        if profile.get("cgpa") is not None and str(profile.get("cgpa")).strip() != "":
            cgpa_value = float(profile.get("cgpa"))
    except (ValueError, TypeError):
        cgpa_value = None

    work_auth_complete = profile.get("work_authorization") in {"Yes", "No"}
    enrollment_complete = profile.get("enrollment_status") in {"CURRENTLY_ENROLLED", "GRADUATED", "NOT_CURRENTLY_ENROLLED"}
    background_complete = profile.get("background_check_status") in {"PASS", "FAIL"}

    mandatory_fields = [
        _is_known_nonempty(profile.get("full_name")),
        _is_known_nonempty(profile.get("degree")),
        cgpa_value is not None and 0.0 <= cgpa_value <= 10.0,
        work_auth_complete,
        profile.get("graduation_year") is not None,
        enrollment_complete,
        background_complete,
    ]

    skills = profile.get("skills") or []
    projects = profile.get("projects") or []
    # Keep the original 3-field optional score stable for benchmark compatibility.
    # Richer profile assets (resume, links, photo, education/work history) are
    # displayed and persisted separately and do not change the legacy score.
    optional_fields = [
        isinstance(skills, list) and len(skills) > 0,
        profile.get("years_experience") is not None or bool(profile.get("work_experience")),
        isinstance(projects, list) and len(projects) > 0,
    ]

    mandatory_pct = int(sum(mandatory_fields) / len(mandatory_fields) * 100)
    optional_pct = int(sum(optional_fields) / len(optional_fields) * 100)
    total_fields = mandatory_fields + optional_fields
    total_pct = int(sum(total_fields) / len(total_fields) * 100)

    return {"mandatory": mandatory_pct, "optional": optional_pct, "total": total_pct}
